### ISSUE TITLE
Removing DBD::mysql from (immediate) dependencies

### ISSUE THREAD

**Issue by mikkoi** [powerman/Narada#5]
>  32 Configuring Narada-v2.2.0 ... OK  
>  33 ==> Found dependencies: Path::Tiny, Test::MockModule, Perl6::Export::Attrs, App::migrate, Test::CheckManifest, DBI, Test::Differences, Test::Exception, DBD::mysql, Pod::Coverage, App::powerdiff, Test::Outpu    t, Test::Pod::Coverage, Test::Perl::Critic, Test::Pod, Log::Fast, File::Copy::Recursive

Narada requires DBD::mysql which in turn requires MySQL binaries ("sudo apt-get install libmysqlclient-dev" in Debian). Could we remove this dependency?

My project does not use MySQL so it is needless to have it installed in the system. Maybe we could move it beyond an eval, e.g. _eval { require DBD::mysql; }_

**Comment by powerman** [comment]
Most of my projects doesn't use MySQL nowadays too, so it's good idea. Sadly, I'm too busy with ongoing work right now and unlikely will have time to implement this small change soon, so if you think you can handle it - send PR.

**Comment by mikkoi** [comment]
Okay. I'll see what I can do. I'm also very busy these days with initializing a new microservice.
